<?php 
/* 
 * Load Helper to get get main settings 
 */

$esatisfaction = Mage::helper('esatisfaction/data');
$application_id = $esatisfaction->getApplicationId();
$questionnaire_id = $esatisfaction->getCheckoutQuestionnaireId();

/* 
 * Get Order Data from esatisfaction block ( Block/Checkout/Success )
 */
$_order_data = $this->getOrderData(); 

?>
<script>
$$(".sub-title").first().insert({ after: '<div id="esat-checkout-questionnaire-container"></div>'});
</script>
<script>
window.esat_config = 
{
	application_id: '<?php echo $application_id; ?>',
	collection: 
	{
		'<?php echo $questionnaire_id; ?>': 
		{
			'questionnaire_id': '<?php echo $questionnaire_id; ?>',
			'metadata': 
			{
				'responder': 
				{
					'email': '<?php echo  $_order_data['email']; ?>',
					'phone_number': '<?php echo  $_order_data['telephone']; ?>'
				},
				'questionnaire': 
				{
					'transaction_id': '<?php echo  $_order_data['increment_id']; ?>',
					'transaction_date': '<?php echo  $_order_data['created_at']; ?>',
					'store_pickup': <?php echo  $_order_data['store_pickup']; ?>
				}
			}
		}
	}
};
</script>