<?php
// Load Helper to get get main settings
$esatisfaction = Mage::helper('esatisfaction/data');
$status = $esatisfaction->getStatus();
if ($status) {
    $questionnaireId = $esatisfaction->getCheckoutQuestionnaireId();

    // Get Order Data from esatisfaction block ( Block/Checkout/Success )
    $orderData = $this->getOrderData();
    ?>
    <script>
        // Update metadata
        Esat.updateMetadata("<?php echo $questionnaireId; ?>", {
            responder: {
                "email": "<?php echo $orderData['email']; ?>",
                "phone_number": "<?php echo $orderData['telephone']; ?>"
            },
            questionnaire: {
                "transaction_id": "<?php echo $orderData['increment_id']; ?>",
                "transaction_date": "<?php echo $orderData['created_at']; ?>",
                "store_pickup": <?php echo $orderData['store_pickup']; ?>
            }
        });

        // Insert checkout container
        $$(".sub-title").first().insert({after: '<div id="esat-checkout-questionnaire-container"></div>'});
    </script>
<?php } ?>
