<?php
$helperData = Mage::helper('esatisfaction/data');
$status = $helperData->getStatus();
if ($status) {
    $applicationId = $helperData->getApplicationId();
    ?>
    <script>
        (function (w, d, id, jq, c) {
            // Define e-satisfaction collection configuration
            w.esat_config = {application_id: id, collection: c || {}};

            // Update metadata
            w.Esat = w.Esat || {};
            w.Esat.updateMetadata = function (q, m) {
                w.esat_config.collection[q] = w.esat_config.collection[q] || {};
                w.esat_config.collection[q].metadata = m;
            };

            // Setup script
            var l = function () {
                var r = d.getElementsByTagName('script')[0], s = d.createElement('script');
                s.async = true;
                s.src = 'https://collection.e-satisfaction.com/dist/js/integration' + (!!jq ? '.jq' : '') + '.min.js';
                r.parentNode.insertBefore(s, r);
            };
            if (w.attachEvent) {
                w.attachEvent('onload', l);
            } else {
                w.addEventListener('load', l, false);
            }
        })(window, document, "<?php echo $applicationId; ?>", "<?php echo $helperData->isJQueryEnabled() ? false : true ?>", {});
    </script>
<?php } ?>
