<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2016 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
  
<script type="text/javascript">
//<![CDATA[
		var buildAuth = function(request,method){
			var public_key = '<?php echo Mage::getStoreConfig('esatisfaction/section_one/esatisfaction_site_public_key'); ?>';
			var private_key = '<?php echo Mage::getStoreConfig('esatisfaction/section_one/esatisfaction_site_private_key'); ?>';
			var timestamp = (new Date().getTime() / 1000).toString();
			
			var hash = CryptoJS.HmacSHA256(public_key+timestamp+ method, private_key);
			var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);
			setHeaders(request, public_key, timestamp, hashInBase64)			
		}     

		var setHeaders = function(request, public_key, timestamp, hashInBase64){
			request.setRequestHeader('X-HASH', hashInBase64);
			request.setRequestHeader('X-Public', public_key);
			request.setRequestHeader('X-Microtime', timestamp);
		}
		
		 var getModuleSettings = function(site_id) {
			$j.ajax({
				type: "GET",
				url:"https://www.e-satisfaction.gr/api/v2/prestashop/get_module_settings/"+site_id,
				contentType: "application/json; charset=utf-8",
				dataType: "json",
				beforeSend: function (request) {
				  buildAuth(request,this.type);
				},    
				success: function (data) {
					if(data){
						if(!data['error']){
							$j('#esatisfaction_section_one_esatisfaction_browse_questions').val(data[0]['config_pg_browse']);
							$j('#esatisfaction_section_one_esatisfaction_checkout_questionnaires').val(data[1]['config_pg_checkout']);
							$j('#esatisfaction_section_one_esatisfaction_after_sales_surveys').val(data[2]['config_pg_aftersales']);
						}
					}
				},
				error: function (errorMessage) {
				   if(errorMessage.status == 401)
					   alert('Access denied');
				}
			});
		};
		
		var site_id = <?php echo Mage::getStoreConfig('esatisfaction/section_one/esatisfaction_site_id'); ?>;
		
		getModuleSettings(site_id);
//]]>
</script>

