<?php
/**
 * Get main settings
 */
$status = $this->_getStatus();
if ($status) {

    $application_id = $this->_getApplicationId();
    $questionnaire_id = $this->_getCheckoutQuestionnaireId();

    /**
     * Get Order Data from esatisfaction block ( Block/Checkout/Success )
     */
    $_order_data = $this->getOrderData();

    ?>
    <script>
        requirejs(['jquery'], function (jQuery) {
            jQuery(".page-title-wrapper").append('<div id="esat-checkout-questionnaire-container"></div>');
        });
    </script>
    <script>
        // Metadata update script
        Esat.updateMetadata("<?php echo $questionnaire_id; ?>", {
                responder:
                    {
                        "email": "<?php echo $_order_data['email']; ?>",
                        "phone_number": "<?php echo $_order_data['telephone']; ?>"
                    },
                questionnaire:
                    {
                        "transaction_id": "<?php echo $_order_data['increment_id']; ?>",
                        "transaction_date": "<?php echo $_order_data['created_at']; ?>",
                        "store_pickup": <?php echo $_order_data['store_pickup']; ?>
                    }
            }
        );
    </script>
<?php } ?>
