<?php

$status = $this->_getStatus();
if ($status) {
    $jquery_installed = $this->_getIsJQueryEnabled();

    if ($jquery_installed) {
        ?>
        <?php
        /*
         * Integration loaded with jquery installed
         */
        ?>
        <script>
            requirejs(['jquery', 'esat'], function (jQuery, esat) {
            });
        </script>

    <?php } else { ?>
        <?php
        /*
         * Integration loaded without jquery installed
         */
        ?>
        <script src="https://collection.e-satisfaction.com/dist/js/integration.min.js"></script>
        <?php
    }
}
?>
